
import java.awt.Color;
import java.util.List;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        displayProductList(productService.findProductList());
    }

    ProductService productService = new ProductServiceImplement();

    public void displayProductList(java.util.List<Product> productList) {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        model.setRowCount(0); // Memulai table dari 0

        for (Product product : productList) {
            Object[] rowData = {
                product.getId(),
                product.getProductName(),
                product.getCategory(),
                product.getQty(),
                product.getPrice(),
                product.getDateAdded()
            };
            model.addRow(rowData); // menambah baris dengan data produk
        }
    }

    public void textBlack() {
        tfProductName.setForeground(new Color(0, 0, 0));
        tfCategory.setForeground(new Color(0, 0, 0));
        tfQty.setForeground(new Color(0, 0, 0));
        tfPrice.setForeground(new Color(0, 0, 0));
        tfDateAdded.setForeground(new Color(0, 0, 0));
    }

    private void sortProductList(String sortBy) {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        List<Product> productList = new ArrayList<>();

        // Mendapatkan daftar produk dari model tabel
        for (int i = 0; i < model.getRowCount(); i++) {
            int id = (int) model.getValueAt(i, 0);
            String productName = (String) model.getValueAt(i, 1);
            String category = (String) model.getValueAt(i, 2);
            int qty = (int) model.getValueAt(i, 3);
            int price = (int) model.getValueAt(i, 4);
            String dateAdded = (String) model.getValueAt(i, 5);

            Product product = new Product(id, productName, category, qty, price, dateAdded);
            productList.add(product);
        }

        // Mengurutkan daftar produk berdasarkan pilihan pengguna
        switch (sortBy) {
            case "ID":
                productList.sort(Comparator.comparing(Product::getId));
                break;
            case "Kategori":
                productList.sort(Comparator.comparing(Product::getCategory));
                break;
            case "Jumlah Stok":
                productList.sort(Comparator.comparingInt(Product::getQty));
                break;
            case "Jumlah Harga":
                productList.sort(Comparator.comparingInt(Product::getPrice));
                break;
        }

        // Memperbarui tampilan tabel dengan daftar produk yang sudah diurutkan
        displayProductList(productList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfProductName = new javax.swing.JTextField();
        tfQty = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelProductId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddProduct = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfDateAdded = new javax.swing.JTextField();
        tfCategory = new javax.swing.JComboBox<>();
        tfSort = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 11))); // NOI18N

        jLabel1.setText("Nama Produk");

        jLabel2.setText("Kategori");

        jLabel3.setText("Jumlah Stok");

        jLabel4.setText("Harga Satuan");

        tfProductName.setForeground(new java.awt.Color(153, 153, 153));
        tfProductName.setText("Nama Produk");
        tfProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfProductNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfProductNameFocusLost(evt);
            }
        });

        tfQty.setForeground(new java.awt.Color(153, 153, 153));
        tfQty.setText("0");
        tfQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfQtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfQtyFocusLost(evt);
            }
        });

        tfPrice.setForeground(new java.awt.Color(153, 153, 153));
        tfPrice.setText("0");
        tfPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPriceFocusLost(evt);
            }
        });

        jLabel5.setText("ID Produk :");

        labelProductId.setBackground(new java.awt.Color(102, 102, 102));
        labelProductId.setForeground(new java.awt.Color(102, 102, 102));

        btnAddProduct.setText("Add");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnUpdateProduct.setText("Update");
        btnUpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProductActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDeleteProduct.setText("Delete");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel7.setText("Tanggal Ditambahkan");

        tfDateAdded.setForeground(new java.awt.Color(153, 153, 153));
        tfDateAdded.setText("dd-mm-yyyy");
        tfDateAdded.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDateAddedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDateAddedFocusLost(evt);
            }
        });

        tfCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Konsumsi", "Pakaian", "Kosmetik", "Minuman" }));

        tfSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Kategori", "Jumlah Stok", "Jumlah Harga" }));
        tfSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSortActionPerformed(evt);
            }
        });

        jLabel6.setText("Urutkan :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfProductName, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(tfQty)
                            .addComponent(tfPrice)
                            .addComponent(tfCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelProductId)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfDateAdded)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tfSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(labelProductId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDateAdded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Produk", "Kategori", "Jumlah Stok", "Harga Satuan", "Tanggal Ditambahkan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        try {
// TODO add your handling code here:
            String productName = tfProductName.getText();
            String category = (String) tfCategory.getSelectedItem();
            String qty = tfQty.getText();
            String price = tfPrice.getText();
            String dateAdded = tfDateAdded.getText();
//        Date parsedDate = Date.parse(dateAdded, formatter);

            if (dateAdded.equals("dd-mm-yyyy")) {
                JOptionPane.showMessageDialog(this, "Barang gagal ditambahkan, form belum lengkap atau tidak sesuai.");
            } else {
                Product newProduct = new Product(0, productName, category, Integer.parseInt(qty), Integer.parseInt(price), dateAdded);
                productService.addProduct(newProduct);

                tfProductName.setText("");
                tfCategory.setSelectedItem(0);
                tfQty.setText("");
                tfPrice.setText("");
                tfDateAdded.setText("");

                displayProductList(productService.findProductList());
                JOptionPane.showMessageDialog(this, "Barang berhasil ditambahkan.");
                textBlack();
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this, "Barang gagal ditambahkan, form belum lengkap atau tidak sesuai.");
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnUpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProductActionPerformed
        try {
            String productName = tfProductName.getText();
            String category = tfCategory.getSelectedItem().toString();
            String qty = tfQty.getText();
            String price = tfPrice.getText();
            String dateAdded = tfDateAdded.getText();
            int selectedRow = productTable.getSelectedRow();
            int productId = (int) productTable.getValueAt(selectedRow, 0);

            Product productUpdate = new Product();
            productUpdate.setId(productId);

            // Setelah mengatur ID, Anda hanya perlu mengatur nilai-nilai yang ingin diperbarui
            productUpdate.setProductName(productName);
            productUpdate.setCategory(category.toString());
            productUpdate.setQty(Integer.parseInt(qty));
            productUpdate.setPrice(Integer.parseInt(price));
            productUpdate.setDateAdded(dateAdded);

            productService.updateProduct(productUpdate);
            tfProductName.setText("");
            tfCategory.setSelectedItem("");
            tfQty.setText("");
            tfPrice.setText("");
            tfDateAdded.setText("");
            displayProductList(productService.findProductList());
            textBlack();

            JOptionPane.showMessageDialog(this, "Barang berhasil di update.");
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this, "Barang gagal diupdate, form belum lengkap atau tidak sesuai.");
        }
    }//GEN-LAST:event_btnUpdateProductActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = productTable.getSelectedRow();
        textBlack();
        if (selectedRow != -1) {
            // Dapatkan data dari baris yang diklik
            int productId = (int) productTable.getValueAt(selectedRow, 0);
            String productName = (String) productTable.getValueAt(selectedRow, 1);
            String category = (String) productTable.getValueAt(selectedRow, 2);
            int qty = (int) productTable.getValueAt(selectedRow, 3);
            int price = (int) productTable.getValueAt(selectedRow, 4);
            String dateAdded = (String) productTable.getValueAt(selectedRow, 5);

            // Update nilai-nilai form dengan data yang diklik
            labelProductId.setText(String.valueOf(productId));
            tfProductName.setText(productName);
            tfCategory.setSelectedItem(category);
            tfQty.setText(String.valueOf(qty));
            tfPrice.setText(String.valueOf(price));
            tfDateAdded.setText(dateAdded);
        }
    }//GEN-LAST:event_productTableMouseClicked

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = productTable.getSelectedRow();
            int productId = (int) productTable.getValueAt(selectedRow, 0);

            productService.removeProduct(productId);

            tfProductName.setText("");
            tfCategory.setSelectedItem("");
            tfQty.setText("");
            tfPrice.setText("");
            tfDateAdded.setText("");
            displayProductList(productService.findProductList());
            textBlack();
            JOptionPane.showMessageDialog(this, "Barang berhasil di hapus.");
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus, klik item pada table untuk menghapus.");
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void tfProductNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProductNameFocusGained
        // TODO add your handling code here:
        if (tfProductName.getText().equals("Nama Produk")) {
            tfProductName.setText("");
            tfProductName.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfProductNameFocusGained

    private void tfProductNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProductNameFocusLost
        // TODO add your handling code here:
        if (tfProductName.getText().equals("")) {
            tfProductName.setText("Nama Produk");
            tfProductName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tfProductNameFocusLost

    private void tfQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQtyFocusGained
        // TODO add your handling code here:
        if (tfQty.getText().equals("0")) {
            tfQty.setText("");
            tfQty.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfQtyFocusGained

    private void tfQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQtyFocusLost
        if (tfQty.getText().equals("")) {
            tfQty.setText("0");
            tfQty.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tfQtyFocusLost

    private void tfPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPriceFocusGained
        // TODO add your handling code here:
        if (tfPrice.getText().equals("0")) {
            tfPrice.setText("");
            tfPrice.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfPriceFocusGained

    private void tfPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPriceFocusLost
        // TODO add your handling code here:
        if (tfPrice.getText().equals("")) {
            tfPrice.setText("0");
            tfPrice.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tfPriceFocusLost

    private void tfDateAddedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDateAddedFocusGained
        // TODO add your handling code here:
        if (tfDateAdded.getText().equals("dd-mm-yyyy")) {
            tfDateAdded.setText("");
            tfDateAdded.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_tfDateAddedFocusGained

    private void tfDateAddedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDateAddedFocusLost
        // TODO add your handling code here:
        if (tfDateAdded.getText().equals("")) {
            tfDateAdded.setText("dd-mm-yyyy");
            tfDateAdded.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_tfDateAddedFocusLost

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        labelProductId.setText("");
        textBlack();

        tfProductName.setText("");

        tfCategory.setSelectedItem("");

        tfQty.setText("");

        tfPrice.setText("");

        tfDateAdded.setText("");

        productTable.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tfSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSortActionPerformed
        // TODO add your handling code here:
        String sortBy = (String) tfSort.getSelectedItem();
        sortProductList(sortBy);
    }//GEN-LAST:event_tfSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // ...
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);

            }
        });
// ...

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelProductId;
    private javax.swing.JTable productTable;
    private javax.swing.JComboBox<String> tfCategory;
    private javax.swing.JTextField tfDateAdded;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfProductName;
    private javax.swing.JTextField tfQty;
    private javax.swing.JComboBox<String> tfSort;
    // End of variables declaration//GEN-END:variables
}
